### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Karyum** [OmklthomAmara/Autocomplete#3]
in some parts of the code errors are not being handled, handling errors is super important 

for example 

https://github.com/OmklthomAmara/Autocomplete/blob/main/handlers/api.js#L12-L14
https://github.com/OmklthomAmara/Autocomplete/blob/main/handlers/sever2RequestData.js#L10-L12

and other places you could reuse the missingHandler function instead of writing

```
      res.writeHead(404, { "content-type": "text/html" });
      res.end("<h1>Not found</h1>");
```

over and over again. instead you can import the missing handler and call it like this 

```
missingHandler(request, repsonse)
```

files that im talking about

https://github.com/OmklthomAmara/Autocomplete/blob/main/handlers/public.js#L20-L24
https://github.com/OmklthomAmara/Autocomplete/blob/main/handlers/home.js#L8-L11

**Comment by OmklthomAmara** [comment]
Fixed 👍
